# Generated by Django 4.1.6 on 2023-03-29 12:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import listings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Remote', 'Remote'), ('Intership', 'Intership')], default='N/A', max_length=250)),
                ('min_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('max_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=5000, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(max_length=250)),
                ('company_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('address', models.CharField(max_length=250)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=500)),
                ('website', models.CharField(blank=True, max_length=1000, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(choices=[('Less than 2yrs', 'Less than 2yrs'), ('2yrs - 5yrs', '2yrs - 5yrs'), ('5yrs - 10yrs', '5yrs - 10yrs'), ('10yrs - 15yrs', '10yrs - 15yrs'), ('More than 15yrs', 'More than 15yrs'), ('N/A', 'N/A')], default='N/A', max_length=250)),
                ('requirements', ckeditor.fields.RichTextField()),
                ('application_mode', models.CharField(blank=True, max_length=250, null=True)),
                ('logo', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=listings.models.Job.logo_dir)),
                ('seo_keywords', models.CharField(blank=True, max_length=2500, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=2500, null=True)),
                ('direct_list', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookmarkJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('bookmarked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jobseeker')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.job')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(choices=[('Less than 2yrs', 'Less than 2yrs'), ('2yrs - 5yrs', '2yrs - 5yrs'), ('5yrs - 10yrs', '5yrs - 10yrs'), ('10yrs - 15yrs', '10yrs - 15yrs'), ('More than 15yrs', 'More than 15yrs'), ('N/A', 'N/A')], default='N/A', max_length=250)),
                ('cover_letter', ckeditor.fields.RichTextField()),
                ('portfolio_link', models.URLField(max_length=500)),
                ('resume', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=listings.models.Applicant.resume_dir)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.job')),
                ('jobseeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jobseeker')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
