# Generated by Django 4.1.6 on 2023-03-29 12:02

import accounts.models
import ckeditor.fields
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Employer'), (3, 'Job seeker')], default=1)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_employer', models.BooleanField(default=False)),
                ('is_jobseeker', models.BooleanField(default=False)),
                ('activate_account', models.BooleanField(default=False)),
                ('terms_and_conditions', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('-', 'Gender'), ('M', 'Male'), ('F', 'Female')], default='-', max_length=1)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('eToken', models.IntegerField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=500, null=True)),
                ('company_industry', models.CharField(choices=[('N/A', 'select industry type'), ('ACCOUNTING', 'Accounting'), ('AIRLINES/AVIATION', 'Airlines/Aviation'), ('ALTERNATIVE DISPUTE RESOLUTION', 'Alternative Dispute Resolution'), ('ALTERNATIVE MEDICINE', 'Alternative Medicine'), ('ANIMATION', 'Animation'), ('APPAREL & FASHION', 'Apparel & Fashion'), ('ARCHITECTURE & PLANNING', 'Architecture & Planning'), ('ARTS & CRAFTS', 'Arts & Crafts'), ('AUTOMOTIVE', 'Automotive'), ('AVIATION & AEROSPACE', 'Aviation & Aerospace'), ('BANKING', 'Banking'), ('BIOTECHNOLOGY', 'Biotechnology'), ('BROADCAST MEDIA', 'Broadcast Media'), ('BUILDING MATERIALS', 'Building Materials'), ('BUSINESS SUPPLIES & EQUIPMENT', 'Business Supplies & Equipment'), ('CAPITAL MARKETS', 'Capital Markets'), ('CHEMICALS', 'Chemicals'), ('CIVIC & SOCIAL ORGANIZATION', 'Civic & Social Organization'), ('CIVIL ENGINEERING', 'Civil Engineering'), ('COMMERCIAL REAL ESTATE', 'Commercial Real Estate'), ('COMPUTER & NETWORK SECURITY', 'Computer & Network Security'), ('COMPUTER GAMES', 'Computer Games'), ('COMPUTER HARDWARE', 'Computer Hardware'), ('COMPUTER NETWORKING', 'Computer Networking'), ('COMPUTER SOFTWARE', 'Computer Software'), ('CONSTRUCTION', 'Construction'), ('CONSUMER ELECTRONICS', 'Consumer Electronics'), ('CONSUMER GOODS', 'Consumer Goods'), ('CONSUMER SERVICES', 'Consumer Services'), ('COSMETICS', 'Cosmetics'), ('DAIRY', 'Dairy'), ('DEFENSE & SPACE', 'Defense & Space'), ('DESIGN', 'Design'), ('EDUCATION MANAGEMENT', 'Education Management'), ('E-LEARNING', 'E-learning'), ('ELECTRICAL & ELECTRONIC MANUFACTURING', 'Electrical & Electronic Manufacturing'), ('ENTERTAINMENT', 'Entertainment'), ('ENVIRONMENTAL SERVICES', 'Environmental Services'), ('EVENTS SERVICES', 'Events Services'), ('EXECUTIVE OFFICE', 'Executive Office'), ('FACILITIES SERVICES', 'Facilities Services'), ('FARMING', 'Farming'), ('FINANCIAL SERVICES', 'Financial Services'), ('FINE ART', 'Fine Art'), ('FISHERY', 'Fishery'), ('FOOD & BEVERAGES', 'Food & Beverages'), ('FOOD PRODUCTION', 'Food Production'), ('FUNDRAISING', 'Fundraising'), ('FURNITURE', 'Furniture'), ('GAMBLING & CASINOS', 'Gambling & Casinos'), ('GLASS, CERAMICS & CONCRETE', 'Glass, Ceramics & Concrete'), ('GOVERNMENT ADMINISTRATION', 'Government Administration'), ('GOVERNMENT RELATIONS', 'Government Relations'), ('GRAPHIC DESIGN', 'Graphic Design'), ('HEALTH, WELLNESS & FITNESS', 'Health, Wellness & Fitness'), ('HIGHER EDUCATION', 'Higher Education'), ('HOSPITAL & HEALTH CARE', 'Hospital & Health Care'), ('HOSPITALITY', 'Hospitality'), ('HUMAN RESOURCES', 'Human Resources'), ('IMPORT & EXPORT', 'Import & Export'), ('INDIVIDUAL & FAMILY SERVICES', 'Individual & Family Services'), ('INDUSTRIAL AUTOMATION', 'Industrial Automation'), ('INFORMATION SERVICES', 'Information Services'), ('INFORMATION TECHNOLOGY & SERVICES', 'Information Technology & Services'), ('INSURANCE', 'Insurance'), ('INTERNATIONAL AFFAIRS', 'International Affairs'), ('INTERNATIONAL TRADE & DEVELOPMENT', 'International Trade & Development'), ('INTERNET', 'Internet'), ('INVESTMENT BANKING/VENTURE', 'Investment Banking/Venture'), ('INVESTMENT MANAGEMENT', 'Investment Management'), ('JUDICIARY', 'Judiciary'), ('LAW ENFORCEMENT', 'Law Enforcement'), ('LAW PRACTICE', 'Law Practice'), ('LEGAL SERVICES', 'Legal Services'), ('LEGISLATIVE OFFICE', 'Legislative Office'), ('LEISURE & TRAVEL', 'Leisure & Travel'), ('LIBRARIES', 'Libraries'), ('LOGISTICS & SUPPLY CHAIN', 'Logistics & Supply Chain'), ('LUXURY GOODS & JEWELRY', 'Luxury Goods & Jewelry'), ('MACHINERY', 'Machinery'), ('MANAGEMENT CONSULTING', 'Management Consulting'), ('MARITIME', 'Maritime'), ('MARKETING & ADVERTISING', 'Marketing & Advertising'), ('MARKET RESEARCH', 'Market Research'), ('MECHANICAL OR INDUSTRIAL ENGINEERING', 'Mechanical or Industrial Engineering'), ('MEDIA PRODUCTION', 'Media Production'), ('MEDICAL DEVICE', 'Medical Device'), ('MEDICAL PRACTICE', 'Medical Practice'), ('MENTAL HEALTH CARE', 'Mental Health Care'), ('MILITARY', 'Military'), ('MINING & METALS', 'Mining & Metals'), ('MOTION PICTURES & FILM', 'Motion Pictures & Film'), ('MUSEUMS & INSTITUTIONS', 'Museums & Institutions'), ('MUSIC', 'Music'), ('NANOTECHNOLOGY', 'Nanotechnology'), ('NEWSPAPERS', 'Newspapers'), ('NONPROFIT ORGANIZATION MANAGEMENT', 'Nonprofit Organization Management'), ('OIL & ENERGY', 'Oil & Energy'), ('ONLINE PUBLISHING', 'Online Publishing'), ('OUTSOURCING/OFFSHORING', 'Outsourcing/Offshoring'), ('PACKAGE/FREIGHT DELIVERY', 'Package/Freight Delivery'), ('PACKAGING & CONTAINERS', 'Packaging & Containers'), ('PAPER & FOREST PRODUCTS', 'Paper & Forest Products'), ('PERFORMING ARTS', 'Performing Arts'), ('PHARMACEUTICALS', 'Pharmaceuticals'), ('PHILANTHROPY', 'Philanthropy'), ('PHOTOGRAPHY', 'Photography'), ('PLASTICS', 'Plastics'), ('POLITICAL ORGANIZATION', 'Political Organization'), ('PRIMARY/SECONDARY', 'Primary/Secondary'), ('PRINTING', 'Printing'), ('PROFESSIONAL TRAINING', 'Professional Training'), ('PROGRAM DEVELOPMENT', 'Program Development'), ('PUBLIC POLICY', 'Public Policy'), ('PUBLIC RELATIONS', 'Public Relations'), ('PUBLIC SAFETY', 'Public Safety'), ('PUBLISHING', 'Publishing'), ('RAILROAD MANUFACTURE', 'Railroad Manufacture'), ('RANCHING', 'Ranching'), ('REAL ESTATE', 'Real Estate'), ('RECREATIONAL', 'Recreational'), ('FACILITIES & SERVICES', 'Facilities & Services'), ('RELIGIOUS INSTITUTIONS', 'Religious Institutions'), ('RENEWABLES & ENVIRONMENT', 'Renewables & Environment'), ('RESEARCH', 'Research'), ('RESTAURANTS', 'Restaurants'), ('RETAIL', 'Retail'), ('SECURITY & INVESTIGATIONS', 'Security & Investigations'), ('SEMICONDUCTORS', 'Semiconductors'), ('SHIPBUILDING', 'Shipbuilding'), ('SPORTING GOODS', 'Sporting Goods'), ('SPORTS', 'Sports'), ('STAFFING & RECRUITING', 'Staffing & Recruiting'), ('SUPERMARKETS', 'Supermarkets'), ('TELECOMMUNICATIONS', 'Telecommunications'), ('TEXTILES', 'Textiles'), ('THINK TANKS', 'Think Tanks'), ('TOBACCO', 'Tobacco'), ('TRANSLATION & LOCALIZATION', 'Translation & Localization'), ('TRANSPORTATION/TRUCKING/RAILROAD', 'Transportation/Trucking/Railroad'), ('UTILITIES', 'Utilities'), ('VENTURE CAPITAL', 'Venture Capital'), ('VETERINARY', 'Veterinary'), ('WAREHOUSING', 'Warehousing'), ('WHOLESALE', 'Wholesale'), ('WINE & SPIRITS', 'Wine & Spirits'), ('WIRELESS', 'Wireless'), ('WRITING & EDITING', 'Writing & Editing')], default='N/A', max_length=250)),
                ('company_type', models.CharField(choices=[('N/A', 'N/A'), ('Direct Employer', 'Direct Employer'), ('Recruitment Agency', 'Recruitment Agency')], default='N/A', max_length=250)),
                ('company_description', ckeditor.fields.RichTextField()),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_employees', models.CharField(choices=[('Less than 2yrs', 'Less than 10'), ('2yrs - 5yrs', '10 - 50'), ('5yrs - 10yrs', '50 - 100'), ('10yrs - 15yrs', '100 - 200'), ('More than 15yrs', 'More than 200'), ('N/A', 'N/A')], default=1, max_length=250)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('logo', models.FileField(blank=True, default='default.png', null=True, upload_to=accounts.models.Employer.logo_dir)),
                ('payment_verified', models.BooleanField(default=False)),
                ('next_payment_date', models.CharField(blank=True, max_length=50, null=True)),
                ('subscribed_to_newsletter', models.BooleanField(default=False)),
                ('security_alert', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(blank=True, max_length=5000, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('summary', ckeditor.fields.RichTextField()),
                ('experience', models.CharField(choices=[('Less than 2yrs', 'Less than 2yrs'), ('2yrs - 5yrs', '2yrs - 5yrs'), ('5yrs - 10yrs', '5yrs - 10yrs'), ('10yrs - 15yrs', '10yrs - 15yrs'), ('More than 15yrs', 'More than 15yrs'), ('N/A', 'N/A')], default='N/A', max_length=250)),
                ('education', models.CharField(blank=True, max_length=50, null=True)),
                ('skills', ckeditor.fields.RichTextField()),
                ('portfolio_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('resume', models.FileField(blank=True, default='default.png', null=True, upload_to=accounts.models.JobSeeker.resume_dir)),
                ('avater', models.FileField(blank=True, default='default.png', null=True, upload_to=accounts.models.JobSeeker.avater_dir)),
                ('display_resume', models.BooleanField(default=False)),
                ('min_salary', models.BigIntegerField()),
                ('max_salary', models.BigIntegerField()),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Remote', 'Remote'), ('Intership', 'Intership'), ('N/A', 'N/A')], default='N/A', max_length=250)),
                ('subscribed_to_newsletter', models.BooleanField(default=False)),
                ('security_alert', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackJobSeeker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uniqueId', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.CharField(blank=True, max_length=50, null=True)),
                ('feedback', ckeditor.fields.RichTextField()),
                ('feedback_reply', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobseeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackEmployer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(blank=True, max_length=50, null=True)),
                ('feedback', ckeditor.fields.RichTextField()),
                ('feedback_reply', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
