# Generated by Django 4.1.6 on 2023-03-29 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(choices=[(0.0, 'select amount'), (5000.0, '#5, 000'), (10000.0, '#10, 000'), (20000.0, 'Pay #20,000 get #30,000'), (30000.0, 'Pay #30,000 get #45, 000'), (50000.0, 'Pay #50, 000 get #75, 000')], decimal_places=2, default=0.0, max_digits=10)),
                ('ref', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('next_payment_date', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.employer')),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
    ]
